description:
  - "Discover my projects where I demonstrate creativity and problem-solving skills."

projects:
  - name: "Project 1"
    description: "A succinct description of the project's purpose and functionality"
    additional_description: "A detailed description on the project's architecture, key components, and any unique selling points. This description should be more comprehensive than the short description."
    date: "Apr 2024"
    svgIcons:
      - gatsby
      - reactjs
      - tailwind
    actions:
      - text: Repo
        color: purple
        link: https://github.com/algebananazzzzz/NocturnalProject

  - name: "Project 2"
    description: "A succinct description of the project's purpose and functionality"
    additional_description: "A detailed description on the project's architecture, key components, and any unique selling points. This description should be more comprehensive than the short description."
    date: "Apr 2024"
    svgIcons:
      - gatsby
      - reactjs
      - tailwind
    actions:
      - text: Repo
        color: purple
        link: https://github.com/algebananazzzzz/NocturnalProject

  - name: "Project 3"
    description: "A succinct description of the project's purpose and functionality"
    additional_description: "A detailed description on the project's architecture, key components, and any unique selling points. This description should be more comprehensive than the short description."
    date: "Apr 2024"
    svgIcons:
      - gatsby
      - reactjs
      - tailwind
    actions:
      - text: Repo
        color: purple
        link: https://github.com/algebananazzzzz/NocturnalProject